# Generated by Django 2.2.7 on 2019-11-19 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('delivery_address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lanme', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Contact PHone')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineStore',
            fields=[
                ('web_address', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Cart')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
